-- Generated by scripts/knowledge.mjs. Do not edit by hand.
-- Deterministic text fallback; production embeddings are populated by biofold-ingest-knowledge.
INSERT INTO public.knowledge_sources
  (id, title, publisher, url, license, retrieved_at, content_path, sha256)
VALUES
  ('biofold-evidence-levels-v1', 'Scientific evidence levels in BioFold', 'BioFold', 'https://github.com/JosueACondoriCh123/BioFold', 'MIT', '2026-09-01', 'knowledge/evidence-levels.md', '5dfca4e25bdd95847fbce42f5e5e27cdbca1c35360e2f78609baf8f46b7be59d'),
  ('biofold-structure-interpretation-v1', 'Interpreting molecular structure context', 'BioFold', 'https://github.com/JosueACondoriCh123/BioFold', 'MIT', '2026-09-01', 'knowledge/structure-interpretation.md', '4a32ae9ccde3f54251e396c2475536bc6892762d0c735ec33503451057af8710')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title, publisher = EXCLUDED.publisher, url = EXCLUDED.url,
  license = EXCLUDED.license, retrieved_at = EXCLUDED.retrieved_at,
  content_path = EXCLUDED.content_path, sha256 = EXCLUDED.sha256;

DELETE FROM public.knowledge_chunks
WHERE source_id IN ('biofold-evidence-levels-v1', 'biofold-structure-interpretation-v1');

INSERT INTO public.knowledge_chunks
  (source_id, chunk_index, title, content, locator, token_count)
VALUES
  ('biofold-evidence-levels-v1', '0', 'Scientific evidence levels in BioFold — Scientific evidence levels in BioFold', 'BioFold separates statements by how they were produced. This distinction must remain visible in the laboratory, persisted project events, citations, and assistant responses.', 'Scientific evidence levels in BioFold', '23'),
  ('biofold-evidence-levels-v1', '1', 'Scientific evidence levels in BioFold — Observed', 'Observed information comes directly from the loaded structural record: atomic coordinates, chain identifiers, residue identifiers, atom names, ligands, and waters. Observed does not mean that every biological interpretation is proven; it means BioFold read the value from the selected structure.', 'Observed', '40'),
  ('biofold-evidence-levels-v1', '2', 'Scientific evidence levels in BioFold — Calculated', 'Calculated information is derived deterministically from observed coordinates or viewer state. Examples include Euclidean atom-to-atom distance, residue counts, neighbors inside a fixed radius, and the representation currently applied. Calculated values should identify their units and input references.', 'Calculated', '37'),
  ('biofold-evidence-levels-v1', '3', 'Scientific evidence levels in BioFold — Heuristic', 'Heuristic information is a qualitative comparison intended to guide exploration. BioFold''s mutation context compares coarse charge, size, and hydrophobicity categories and identifies spatial neighbors in the static structure. It does not predict stability, folding, binding affinity, pathogenicity, or clinical effect.', 'Heuristic', '40'),
  ('biofold-evidence-levels-v1', '4', 'Scientific evidence levels in BioFold — Unavailable', 'Unavailable indicates that BioFold could not obtain or verify the requested evidence. The assistant must say what is missing and must not replace the missing result with an invented scientific claim.', 'Unavailable', '31'),
  ('biofold-structure-interpretation-v1', '0', 'Interpreting molecular structure context — Interpreting molecular structure context', 'A molecular structure is a model of coordinates under specific experimental or computational conditions. BioFold uses the selected PDB entry as the coordinate source and should identify that entry in every structure-specific explanation.

Representations such as cartoon, stick, sphere, and line change how the same coordinates are displayed. They do not change the molecule or produce a new structure. Molecular surfaces are computed visual overlays and their opacity is only a rendering parameter.

An atom-to-atom distance is a Euclidean calculation between two unambiguous coordinates and is reported in ångströms. A neighborhood search reports residues with atoms inside a stated cutoff. These measurements describe the loaded static coordinates and should not be presented as molecular dynamics.

RCSB PDB metadata and UniProt annotations add biological context, but the assistant must cite the exact source and distinguish database annotation from a calculation performed by BioFold. If sources disagree or mapping is ambiguous, the uncertainty must remain explicit.', 'Interpreting molecular structure context', '154');
