import { describe, it, expect, vi, beforeEach } from "vitest";
import {
  generateMarkdownReport,
  generateHtmlReport,
  openPrintableReportWindow,
  type ScientificReportCompilation,
} from "../../src/services/scientificReportService";

const mockFullCompilation: ScientificReportCompilation = {
  title: "SARS-CoV-2 Main Protease Structural Dossier",
  projectTitle: "COVID-19 Antiviral Project",
  author: "Dr. BioFold",
  date: "September 4, 2026",
  structure: {
    pdbId: "6LU7",
    name: "Mpro in complex with N3 inhibitor",
    organism: "SARS-CoV-2",
    method: "X-ray Diffraction",
    resolution: "2.16 Å",
    chainCount: 2,
    residueCount: 306,
    atomCount: 2370,
    ligandCount: 2,
  },
  viewStyle: {
    representation: "cartoon",
    colorScheme: "chain",
  },
  figureDataUrl:
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
  measurements: [
    {
      from: "CYS 145 SG",
      to: "HIS 41 NE2",
      angstroms: 3.75,
    },
  ],
  mutations: [
    {
      residue: "A:145",
      original: "CYS",
      target: "ALA",
      neighborCount: 8,
      heuristics: [
        { dimension: "Steric Clashes", note: "Loss of catalytic nucleophile" },
      ],
    },
  ],
  annotations: [
    {
      type: "catalytic",
      label: "A:145 (Cys)",
      detail: "Nucleophilic cysteine",
    },
    {
      type: "bookmark",
      label: "A:166",
      detail: "Glu166 salt bridge with N-terminus",
    },
  ],
  copilotSummary:
    "The catalytic dyad (Cys145-His41) is positioned in close proximity (3.75 Å) with covalent inhibitor N3 anchored firmly into the catalytic pocket.",
};

describe("scientificReportService", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  describe("generateMarkdownReport", () => {
    it("generates structured markdown containing all dossier sections", () => {
      const md = generateMarkdownReport(mockFullCompilation);

      // Title and metadata
      expect(md).toContain("# SARS-CoV-2 Main Protease Structural Dossier");
      expect(md).toContain("**Project:** COVID-19 Antiviral Project");
      expect(md).toContain("**Target Structure:** 6LU7 (Mpro in complex with N3 inhibitor)");
      expect(md).toContain("**Generated:** September 4, 2026");
      expect(md).toContain("**Researcher:** Dr. BioFold");

      // Specifications
      expect(md).toContain("## 1. Macromolecular Specifications");
      expect(md).toContain("| **PDB / Model ID** | `6LU7` |");
      expect(md).toContain("| **Resolution** | 2.16 Å |");
      expect(md).toContain("| **Polypeptide Chains** | 2 |");
      expect(md).toContain("| **Visualization Mode** | cartoon (Color: chain) |");

      // High-res figure
      expect(md).toContain("## 2. 3D Structural Architecture");
      expect(md).toContain("![Structure 6LU7](data:image/png;base64,");

      // Atomic measurements
      expect(md).toContain("## 3. Atomic Distance Measurements");
      expect(md).toContain("| 1 | `CYS 145 SG` | `HIS 41 NE2` | **3.75 Å** |");

      // Mutations
      expect(md).toContain("## 4. In Silico Variant Benchmark (Workbench)");
      expect(md).toContain("| `A:145` | **CYS** | **ALA** | 8 residues | • **Steric Clashes**: Loss of catalytic nucleophile |");

      // Annotations & Bookmarks
      expect(md).toContain("## 5. Functional Annotations & Curated 3D Bookmarks");
      expect(md).toContain("| **Catalytic Site** | `A:145 (Cys)` | Nucleophilic cysteine |");
      expect(md).toContain("| **3D Bookmark** | `A:166` | Glu166 salt bridge with N-terminus |");

      // Copilot assessment
      expect(md).toContain("## 6. AI Research Copilot Findings & Scientific Assessment");
      expect(md).toContain("The catalytic dyad (Cys145-His41) is positioned in close proximity");

      // Footer
      expect(md).toContain("Generated by BioFold 3D");
    });

    it("handles minimal report with empty optional sections gracefully", () => {
      const minimalCompilation: ScientificReportCompilation = {
        title: "Minimal Report",
        structure: {
          pdbId: "1CRN",
        },
      };

      const md = generateMarkdownReport(minimalCompilation);

      expect(md).toContain("# Minimal Report");
      expect(md).toContain("**Target Structure:** 1CRN");
      expect(md).not.toContain("## 2. 3D Structural Architecture");
      expect(md).not.toContain("## 3. Atomic Distance Measurements");
      expect(md).not.toContain("## 4. In Silico Variant Benchmark (Workbench)");
      expect(md).not.toContain("## 5. Functional Annotations & Curated 3D Bookmarks");
      expect(md).not.toContain("## 6. AI Research Copilot Findings & Scientific Assessment");
    });
  });

  describe("generateHtmlReport", () => {
    it("generates publication-ready HTML containing @media print rules and layout tags", () => {
      const html = generateHtmlReport(mockFullCompilation);

      expect(html).toContain("<!DOCTYPE html>");
      expect(html).toContain("<title>SARS-CoV-2 Main Protease Structural Dossier - 6LU7</title>");
      expect(html).toContain("@page {");
      expect(html).toContain("size: A4 portrait;");
      expect(html).toContain("@media print");
      expect(html).toContain("SARS-CoV-2 Main Protease Structural Dossier");
      expect(html).toContain("6LU7");
      expect(html).toContain("3.75 Å");
      expect(html).toContain("CYS 145 SG");
      expect(html).toContain("The catalytic dyad");
    });
  });

  describe("openPrintableReportWindow", () => {
    it("opens a print window, writes document and triggers print", () => {
      const mockPrint = vi.fn();
      const mockClose = vi.fn();
      const mockWrite = vi.fn();

      const mockWindow = {
        document: {
          open: vi.fn(),
          write: mockWrite,
          close: vi.fn(),
        },
        focus: vi.fn(),
        print: mockPrint,
        close: mockClose,
        onload: null as (() => void) | null,
      };

      vi.spyOn(window, "open").mockReturnValue(mockWindow as unknown as Window);

      const opened = openPrintableReportWindow(mockFullCompilation);

      expect(opened).toBe(true);
      expect(window.open).toHaveBeenCalledWith("", "_blank");
      expect(mockWrite).toHaveBeenCalled();

      // Trigger onload callback
      if (mockWindow.onload) {
        (mockWindow.onload as () => void)();
        expect(mockPrint).toHaveBeenCalled();
      }
    });

    it("returns false if popup is blocked by the browser", () => {
      vi.spyOn(window, "open").mockReturnValue(null);

      const opened = openPrintableReportWindow(mockFullCompilation);
      expect(opened).toBe(false);
    });
  });
});
