import { createHash } from "node:crypto";
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const knowledgeRoot = join(repositoryRoot, "knowledge");
const manifestPath = join(knowledgeRoot, "manifest.json");
const payloadPath = join(knowledgeRoot, "generated", "corpus-v2.json");
const seedPath = join(repositoryRoot, "supabase", "seed.sql");

const sha256 = (value) => createHash("sha256").update(value, "utf8").digest("hex");
const json = (value) => `${JSON.stringify(value, null, 2)}\n`;

export function normalizeMarkdown(value) {
  const lines = value.normalize("NFC").replace(/\r\n?/g, "\n").split("\n").map((line) => line.trimEnd());
  const blocks = [];
  let paragraph = [];
  const flush = () => {
    if (!paragraph.length) return;
    blocks.push(paragraph.join(" ").replace(/\s+/g, " ").trim());
    paragraph = [];
  };
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) { flush(); continue; }
    if (/^#{1,6}\s+\S/.test(trimmed)) { flush(); blocks.push(trimmed.replace(/\s+/g, " ")); }
    else paragraph.push(trimmed);
  }
  flush();
  return `${blocks.join("\n\n").trim()}\n`;
}

function wordCount(value) {
  return value.trim() ? value.trim().split(/\s+/u).length : 0;
}

function splitOversized(value, maxCharacters, maxWords) {
  const sentences = value.split(/(?<=[.!?])\s+/u);
  const pieces = [];
  let current = "";
  const pushCurrent = () => { if (current) pieces.push(current); current = ""; };
  const appendWords = (text) => {
    for (const word of text.split(/\s+/u).filter(Boolean)) {
      const candidate = current ? `${current} ${word}` : word;
      if (candidate.length > maxCharacters || wordCount(candidate) > maxWords) pushCurrent();
      if (word.length <= maxCharacters) current = current ? `${current} ${word}` : word;
      else {
        for (let offset = 0; offset < word.length; offset += maxCharacters) pieces.push(word.slice(offset, offset + maxCharacters));
      }
    }
  };
  for (const sentence of sentences) {
    const candidate = current ? `${current} ${sentence}` : sentence;
    if (candidate.length <= maxCharacters && wordCount(candidate) <= maxWords) current = candidate;
    else { pushCurrent(); appendWords(sentence); }
  }
  pushCurrent();
  return pieces;
}

export function chunkMarkdown(value, limits) {
  const blocks = normalizeMarkdown(value).trim().split(/\n\n/u).filter(Boolean);
  const chunks = [];
  let heading = "Document";
  let current = "";
  const flush = () => {
    if (!current) return;
    chunks.push({ locator: heading, content: current, wordCount: wordCount(current), checksum: sha256(current) });
    current = "";
  };
  for (const block of blocks) {
    if (/^#{1,6}\s+/.test(block)) { flush(); heading = block.replace(/^#{1,6}\s+/, ""); continue; }
    for (const piece of splitOversized(block, limits.maxCharacters, limits.maxWords)) {
      const candidate = current ? `${current}\n\n${piece}` : piece;
      if (candidate.length > limits.maxCharacters || wordCount(candidate) > limits.maxWords) flush();
      current = current ? `${current}\n\n${piece}` : piece;
    }
  }
  flush();
  return chunks;
}

function sqlLiteral(value) {
  return value === null || value === undefined ? "NULL" : `'${String(value).replaceAll("'", "''")}'`;
}

function buildSeed(payload) {
  const sourceRows = payload.sources.map((source) => `  (${[
    source.id, source.title, source.publisher, source.url, source.license, source.retrievedAt,
    source.contentPath, source.checksum,
  ].map(sqlLiteral).join(", ")})`).join(",\n");
  const chunkRows = payload.sources.flatMap((source) => source.chunks.map((chunk) => `  (${[
    source.id, chunk.index, chunk.title, chunk.content, chunk.locator, chunk.wordCount,
  ].map(sqlLiteral).join(", ")})`)).join(",\n");
  return `-- Generated by scripts/knowledge.mjs. Do not edit by hand.\n-- Deterministic text fallback; production embeddings are populated by biofold-ingest-knowledge.\nINSERT INTO public.knowledge_sources\n  (id, title, publisher, url, license, retrieved_at, content_path, sha256)\nVALUES\n${sourceRows}\nON CONFLICT (id) DO UPDATE SET\n  title = EXCLUDED.title, publisher = EXCLUDED.publisher, url = EXCLUDED.url,\n  license = EXCLUDED.license, retrieved_at = EXCLUDED.retrieved_at,\n  content_path = EXCLUDED.content_path, sha256 = EXCLUDED.sha256;\n\nDELETE FROM public.knowledge_chunks\nWHERE source_id IN (${payload.sources.map((source) => sqlLiteral(source.id)).join(", ")});\n\nINSERT INTO public.knowledge_chunks\n  (source_id, chunk_index, title, content, locator, token_count)\nVALUES\n${chunkRows};\n`;
}

async function expectedArtifacts() {
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  if (manifest.schemaVersion !== 2) throw new Error("knowledge/manifest.json must use schemaVersion 2.");
  if (manifest.embedding?.model !== "gte-small" || manifest.embedding?.dimensions !== 384) throw new Error("The corpus must use normalized 384D gte-small embeddings.");
  const limits = manifest.chunking;
  if (limits?.maxCharacters !== 1200 || limits?.maxWords !== 180) throw new Error("Chunk limits must be 1,200 characters and 180 words.");
  const sources = [];
  for (const source of manifest.sources) {
    const sourcePath = resolve(knowledgeRoot, source.contentPath);
    if (!sourcePath.startsWith(knowledgeRoot)) throw new Error(`Source path escapes knowledge/: ${source.contentPath}`);
    const normalized = normalizeMarkdown(await readFile(sourcePath, "utf8"));
    const chunks = chunkMarkdown(normalized, limits).map((chunk, index) => ({
      index,
      title: `${source.title} — ${chunk.locator}`,
      ...chunk,
    }));
    if (chunks.some((chunk) => chunk.content.length > limits.maxCharacters || chunk.wordCount > limits.maxWords)) throw new Error(`Chunk limits failed for ${source.id}.`);
    sources.push({
      id: source.id, title: source.title, publisher: source.publisher, url: source.url,
      license: source.license, retrievedAt: source.retrievedAt,
      contentPath: relative(repositoryRoot, sourcePath).replaceAll("\\", "/"),
      checksum: sha256(normalized), chunks,
    });
  }
  const payload = {
    schemaVersion: 2,
    corpusVersion: manifest.corpusVersion,
    embedding: manifest.embedding,
    normalization: manifest.normalization,
    chunking: manifest.chunking,
    sources,
  };
  const payloadText = json(payload);
  const seedText = buildSeed(payload);
  const nextManifest = {
    ...manifest,
    sources: manifest.sources.map((source) => ({ ...source, sha256: sources.find((item) => item.id === source.id).checksum })),
    artifacts: {
      payloadPath: "./generated/corpus-v2.json",
      payloadSha256: sha256(payloadText),
      seedPath: "../supabase/seed.sql",
      seedSha256: sha256(seedText),
    },
  };
  return { manifestText: json(nextManifest), payloadText, seedText };
}

export async function buildKnowledge() {
  const expected = await expectedArtifacts();
  await mkdir(dirname(payloadPath), { recursive: true });
  await Promise.all([
    writeFile(manifestPath, expected.manifestText),
    writeFile(payloadPath, expected.payloadText),
    writeFile(seedPath, expected.seedText),
  ]);
  console.log("Built deterministic corpus v2, payload, and Supabase seed.");
}

export async function checkKnowledge() {
  const expected = await expectedArtifacts();
  const actual = await Promise.all([manifestPath, payloadPath, seedPath].map((path) => readFile(path, "utf8").catch(() => null)));
  const labels = [manifestPath, payloadPath, seedPath];
  const mismatches = actual.flatMap((value, index) => value === [expected.manifestText, expected.payloadText, expected.seedText][index] ? [] : [relative(repositoryRoot, labels[index])]);
  if (mismatches.length) throw new Error(`Knowledge artifacts are stale: ${mismatches.join(", ")}. Run pnpm knowledge:build.`);
  console.log("Knowledge manifest, hashes, payload, and seed are reproducible.");
}

async function ingest() {
  await checkKnowledge();
  const token = process.env.BIOFOLD_INGEST_TOKEN;
  const endpoint = process.env.BIOFOLD_INGEST_URL ?? (process.env.SUPABASE_URL ? `${process.env.SUPABASE_URL.replace(/\/$/, "")}/functions/v1/biofold-ingest-knowledge` : undefined);
  if (!token || !endpoint) throw new Error("Set BIOFOLD_INGEST_TOKEN and BIOFOLD_INGEST_URL (or SUPABASE_URL).");
  const response = await fetch(endpoint, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: await readFile(payloadPath, "utf8"),
  });
  const body = await response.text();
  if (!response.ok) throw new Error(`Knowledge ingestion failed with HTTP ${response.status}: ${body.slice(0, 500)}`);
  console.log(body);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const command = process.argv[2];
  if (command === "build") await buildKnowledge();
  else if (command === "check") await checkKnowledge();
  else if (command === "ingest") await ingest();
  else throw new Error("Usage: node scripts/knowledge.mjs <build|check|ingest>");
}
